<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.0.2" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Markdig" Version="0.41.3" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="NAudio" Version="2.3.0" />
    <PackageVersion Include="Novolis.Analyzers.StackBoundaries" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Audio.Voice.EdgeTts" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Avalonia.Markdown" Version="2026.1.*" />
    <PackageVersion Include="Novolis.IO.Git" Version="2026.1.*" />
    <PackageVersion Include="Novolis.IO.GitHub" Version="2026.1.*" />
    <PackageVersion Include="Novolis.IO.Paths" Version="2026.1.*" />
    <PackageVersion Include="Novolis.IO.Recovery" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Markup.Markdown.Rendering" Version="2026.1.*" />
    <PackageVersion Include="QuestPDF" Version="2025.7.4" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
